### ISSUE TITLE
The last package release 0.4 on Pypi is broken.

### ISSUE THREAD

**Issue by cleberjsantos** [collective/pas.plugins.sqlalchemy#19]
Some contents are missing in the Pypi package and here in [git](https://github.com/collective/pas.plugins.sqlalchemy/tree/0.4/src/pas/plugins/sqlalchemy) there exists.

### Contents that are missing.

- profiles
- templates
- configure.zcml

**Comment by jensens** [comment]
usually a bad managed MANIFEST.in - should be modernized according to the bobtemplates.plone way.

**Comment by malthe** [comment]
ouch

**Comment by keul** [comment]
Suffered of the same issue today... this has been fixed probably here: https://github.com/collective/pas.plugins.sqlalchemy/commit/88b01689becef942dd19849dd97297e7280e913b

Unluckily no CHANGES info has been registered.

Anyone can release a 0.4.1?

**Comment by malthe** [comment]
Done.

**Comment by keul** [comment]
@malthe I'm really sorry, I just manually checked MANIFEST without testing it... Changes to MANIFEST were not right.

*Now* I fixed the MANIFEST (and tested with zest.releaser), but 0.4.1 is still a brown bag.

Sorry again.

**Comment by malthe** [comment]
Done!
